source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "jdugan6240/powerline.kak" config %{
    powerline-start
}


plug "andreyorst/smarttab.kak" defer smarttab %{
    # when `backspace' is pressed, 4 spaces are deleted at once
    set-option global softtabstop 4
} config %{
    # these languages will use `expandtab' behavior
    hook global WinSetOption filetype=(rust|markdown|kak|lisp|scheme|sh|perl) expandtab
    # these languages will use `noexpandtab' behavior
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
    # these languages will use `smarttab' behavior
    hook global WinSetOption filetype=(c|cpp) smarttab
}

plug "andreyorst/kaktree" defer kaktree %{
    set-option global kaktree_double_click_duration '0.5'
    set-option global kaktree_indentation 1
    set-option global kaktree_dir_icon_open  '▾ 🗁 '
    set-option global kaktree_dir_icon_close '▸ 🗀 '
    set-option global kaktree_file_icon      '⠀⠀🖺'
} config %{...}

plug "alexherbo2/auto-pairs.kak"

plug "andreyorst/fzf.kak" defer fzf %{
    set-option global fzf_file_command 'fd'
    set-option global fzf_highlight_command 'bat'
}
map global normal <c-r> ': fzf-mode<ret>'

add-highlighter global/ number-lines -relative
add-highlighter global/ wrap
add-highlighter global/ show-matching

# Set jumpclient
set-option global jumpclient jump
# Set toolsclient
set-option global toolsclient tools
# Set docsclient
set-option global docsclient docs
