#!/bin/sh

DIS1=eDP-1
DIS2=HDMI-1


choices="laptop\nlaptopdual\nHDMI\nManual selection"

chosen=$(echo -e "$choices" | dmenu -i)

case "$chosen" in
	laptopdual) xrandr --output $DIS1 --auto --output $DIS2 --auto --right-of $DIS1 ;;
	laptop) xrandr --output $DIS1 --auto --output $DIS2 --off ;;
	HDMI) xrandr --output $DIS2 --auto --output $DIS1 --off ;;
	"Manual selection") arandr ;;
esac

# Relaunch polybar if there was a selection.
[ "$chosen" == "" ] || ~/.config/polybar/launch.sh
